// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjB-Tx1QQ2Jx8SccixwykE-dwxdlwYT_c',
    appId: '1:1077604232697:web:823c71ca22e25dac7c2128',
    messagingSenderId: '1077604232697',
    projectId: 'principito-app',
    authDomain: 'principito-app.firebaseapp.com',
    storageBucket: 'principito-app.firebasestorage.app',
    measurementId: 'G-LGM2KD9D8T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7LkVmFL3dXLZeCO4nQhoaqaRN03GMH0Y',
    appId: '1:1077604232697:android:4f2b69450edab95c7c2128',
    messagingSenderId: '1077604232697',
    projectId: 'principito-app',
    storageBucket: 'principito-app.firebasestorage.app',
  );

}